// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://orzrzlmcjllkdckdvgwt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9yenJ6bG1jamxsa2Rja2R2Z3d0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NDg0ODksImV4cCI6MjA2OTUyNDQ4OX0.yvCXqgI23m7uUXIsKhViTCzoPL9XY7k8zNG88TOJ2nA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});